import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/sidebar/sidebar";
import GlobalStyleProvider from "./_providers/globalStyleProvider";
import ContextProvider from "./_providers/contextProvider";
import {ClerkProvider, auth} from "@clerk/nextjs";
import NextTopLoader from "nextjs-toploader";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700", "500", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  const {userId} = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body className={nunito.className}>
          <NextTopLoader
            height={2}
            color="#27ae60"
            easing="cubic-bezier(0.53, 0.21, 0, 1)"
            showSpinner={false}
          />
          <ContextProvider>
            <GlobalStyleProvider>
              {userId && <Sidebar />}
              <div className="w-full">{children}</div>
            </GlobalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
